### ISSUE TITLE
k8s: vCPUs are not connected

### ISSUE THREAD

**Issue by devimc** [kata-containers/agent#239]
# Description of problem

* Run a container with a CPU constraints of 3 CPUs.
* Inside the container at least 3 CPUs should be visible and connected.

*~/cpu-demo.yaml*
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: sandbox
spec:
  containers:
  - name: cpu0
    image: debian
    resources:
      limits:
        cpu: "3"
    args:
    - "bash"
    tty: true
    stdin: true
```

```
$ sudo -E kubectl create -f ~/cpu-demo.yaml
```

# Expected result

```
$ nproc
4
```

# Actual result

```
$ nrpoc
1
```
