### ISSUE TITLE
PID namespace is not being shared between containers in a pod 

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/agent#261]
Using the following `pod.yaml`
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  shareProcessNamespace: true
  containers:
  - name: first-test-container
    image: busybox
    command:
        - sleep
        - "10"
  - name: second-test-container
    image: busybox
    command:
        - sleep
        - "10"
    stdin: true
    tty: true
```
And then:
```
$ sudo -E kubectl create -f pod.yaml
$ sudo -E kubectl exec busybox -c first-test-container ps
PID   USER     TIME  COMMAND
    1 root      0:00 sleep 10
    5 root      0:00 ps
$ sudo -E kubectl exec busybox -c second-test-container ps 
PID   USER     TIME  COMMAND
    1 root      0:00 sleep 10
    5 root      0:00 ps
```
As we can see the PID namespace is not being shared. 

This is the configuration that I am using:
```
kata-runtime : 1.0.0
commit : 329f70463a0a6a5c02da61801987ca4247094424
OCI specs: 1.0.1
kata-shim version 1.0.0-087a5371680f069d45baed8544a09b4e6353c06e
kata-proxy version 1.0.0-a69326b63802952b14203ea9c1533d4edb8c1d64
kata-agent version 1.0.0-f6db83c952e3042ed7b527a1bd576e6b888f4f75
kubectl v1.10.0
```

I also tried to do the suggestions from https://github.com/kata-containers/tests/issues/336 but this problem is still there.
