### ISSUE TITLE
CI: add proto review group into CODEOWNERS file

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/agent#460]
During the move from pullapprove, I think we lost the special group of folks who need to review any grpc proto changes. Let's add them back in by making the appropriate CODEOWNERS file update.

**Comment by grahamwhaley** [comment]
for ref, this is what the old pullapprove config looked like:

```yaml
protocol-changes:
    required: 2
    teams:
      - architecture-committee
      - builder
      - packaging
    conditions:
      files:
        include:
          - "*.proto"
        exclude:
          - "vendor/*"
```
