### ISSUE TITLE
Kubernetes emptyDir does not have correct permissions

### ISSUE THREAD

**Issue by awprice** [kata-containers/agent#636]
# Description of problem

When using Kubernetes emptyDir in Kata, the directory that is created inside the container does not have the correct permissions. This becomes an issue when using non-root users inside the container, as they won't be able to write to the directory.

We set the mode in the options for the local storage in the runtime to `0777` but it doesn't seem to be respected - https://github.com/kata-containers/runtime/blob/master/virtcontainers/kata_agent.go#L88

# Expected result

For the emptyDir directory permissions to be `0777`. This is what happens when running inside a regular runc container:

```
$ ls -lh /opt/
total 4.0K
drwxrwxrwx. 2 root root 4.0K Aug 28 03:54 test
```

# Actual result

The emptyDir directory permissions are set to `0755` when running inside a Kata container:

```
$ ls -lh /opt/ 
total 4.0K
drwxr-xr-x 2 root root 4.0K Aug 28 03:51 test
```

# Pod Spec

The following pod spec was used for the above results:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: default
  annotations:
    io.kubernetes.cri.untrusted-workload: "true"
spec:
  containers:
    - image: ubuntu:18.04
      name: "test"
      command:
        - sleep
        - "3600"
      volumeMounts:
        - mountPath: /opt/test
          name: test
  volumes:
    - name: test
      emptyDir: {}
```
